{% set version = "4.3.2" %}

package:
  name: decorator
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/decorator/decorator-{{ version }}.tar.gz
  sha256: 33cd704aea07b4c28b3eb2c97d288a06918275dac0ecebdaf1bc8a48d98adb9e

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - decorator

about:
  home: https://github.com/micheles/decorator
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Better living through Python with decorators.'
  description: |
    Preserve the signature of decorated functions in a consistent way
    across Python releases.
  doc_url: http://decorator.readthedocs.io/en/stable/
  doc_source_url: https://github.com/micheles/decorator/tree/master/docs
  dev_url: https://github.com/micheles/decorator

extra:
  recipe-maintainers:
    - msarahan
    - pelson
    - ocefpaf
    - scopatz
