{% set version = "4.2.1" %}

package:
  name: decorator
  version: {{ version }}

source:
  fn: decorator-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/decorator/decorator-{{ version }}.tar.gz
  sha256: 7d46dd9f3ea1cf5f06ee0e4e1277ae618cf48dfb10ada7c8427cd46c42702a0e

build:
  number: 0
  script: python -m pip install --no-deps .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - decorator

about:
  home: https://github.com/micheles/decorator
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Better living through Python with decorators.'

extra:
  recipe-maintainers:
    - msarahan
    - pelson
    - ocefpaf
    - scopatz
