{% set name = "decorator" %}
{% set version = "5.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 65f266143752f734b0a7cc83c46f4618af75b8c5911b00ccb61d0ac9b6da0360

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - decorator
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -ra -vvv tests/test.py

about:
  home: https://github.com/micheles/decorator
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Better living through Python with decorators.
  description: |
    Preserve the signature of decorated functions in a consistent way
    across Python releases.
  doc_url: https://github.com/micheles/decorator/blob/master/docs/documentation.md
  dev_url: https://github.com/micheles/decorator

extra:
  recipe-maintainers:
    - msarahan
    - pelson
    - ocefpaf
    - scopatz
