{% set version = "5.0.4" %}

package:
  name: decorator
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/decorator/decorator-{{ version }}.tar.gz
  sha256: cdd9d86d8aca11e4496f3cd26d48020db5a2fac247af0e918b3e0bbdb6e4a174

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5 

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - decorator

about:
  home: https://github.com/micheles/decorator
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Better living through Python with decorators.
  description: |
    Preserve the signature of decorated functions in a consistent way
    across Python releases.
  doc_url: http://decorator.readthedocs.io/en/stable/
  doc_source_url: https://github.com/micheles/decorator/tree/master/docs
  dev_url: https://github.com/micheles/decorator

extra:
  recipe-maintainers:
    - msarahan
    - pelson
    - ocefpaf
    - scopatz
