{% set version = "5.1.1" %}

package:
  name: decorator
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/decorator/decorator-{{ version }}.tar.gz
  sha256: 637996211036b6385ef91435e4fae22989472f9d571faba8927ba8253acbc330

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - decorator

about:
  home: https://github.com/micheles/decorator
  license: BSD-2-Clause
  license_file: LICENSE.txt
  summary: Better living through Python with decorators.
  description: |
    Preserve the signature of decorated functions in a consistent way
    across Python releases.
  doc_url: https://github.com/micheles/decorator/blob/master/docs/documentation.md
  doc_source_url: https://github.com/micheles/decorator/tree/master/docs
  dev_url: https://github.com/micheles/decorator

extra:
  recipe-maintainers:
    - msarahan
    - pelson
    - ocefpaf
    - scopatz
