{% set version = "4.0.11" %}

package:
  name: decorator
  version: {{ version }}

source:
  fn: decorator-{{ version }}.tar.gz
  url: https://github.com/micheles/decorator/archive/{{ version }}.tar.gz
  sha256: cb2d6dfefe7905e9382afd06fee132da5adda30f3846d1cfad0da3e02b3f248a

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - decorator

about:
  home: https://github.com/micheles/decorator
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Better living through Python with decorators.'

extra:
  recipe-maintainers:
    - msarahan
    - pelson
    - ocefpaf
    - scopatz
